import{GAME_CONFIG as C}from'../config.js';
import{LIVE_ACTIONS,executeLiveAction}from'./actions.js';
let session=null,lastSeen=0,panelPresent=false;
const $=id=>document.getElementById(id),clean=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8),format=v=>{const c=clean(v);return c.length>4?c.slice(0,4)+'-'+c.slice(4):c};
function traceId(d={}){return String(d.traceId||d.commandId||d.eventId||d.deliveryId||d.id||'').trim()}
function emit(){window.dispatchEvent(new CustomEvent('railrush-live-status',{detail:{connected:panelPresent,transport:session?.getTransport?.()||'offline'}}))}
function status(text,kind=''){const a=$('panelStatus'),b=$('pairMessage');if(a)a.textContent=text;if(b){b.textContent=text;b.className='pair-message '+kind}emit()}
function manifest(){return{protocol:'liveplus-game-manifest-v1',gameId:C.gameId,name:C.name,icon:'RR',version:C.version,actions:LIVE_ACTIONS}}
function resolveConnection(raw=''){const text=String(raw||'').trim(),sdk=window.LivePlusGameSDK,ticket=sdk?.parseTicket?.(text)||null;if(ticket){sdk.configureRelay?.(ticket.endpoint);return{code:clean(ticket.code),value:text}}const code=clean(text);return{code,value:code}}
function ack(phase,data={},extra={}){try{session?.sendState?.({scope:'diagnostic',gameId:C.gameId,version:C.version,traceId:traceId(data),commandId:String(data.commandId||''),action:String(data.action||data.command||''),phase,at:Date.now(),...extra})}catch{}}
async function onCommand(data={}){panelPresent=true;lastSeen=Date.now();status('Conectado','ok');const action=String(data.action||data.command||'');ack('received',data);const t=performance.now();let ok=false,error='';try{ok=!!(await executeLiveAction(action))}catch(err){error=String(err?.message||err)}ack(ok?'executed':'failed',data,{executionMs:Number((performance.now()-t).toFixed(2)),error});window.dispatchEvent(new CustomEvent('railrush-live-action',{detail:{action,ok,user:data.username||data.uniqueId||''}}));}
export async function connectPanel(raw){if(!window.LivePlusGameSDK?.Session){status('SDK Live+ não carregou','err');return false}const input=$('panelCode'),target=resolveConnection(raw??input?.value??''),code=target.code;if(input)input.value=format(code);if(code.length!==8){status('Código inválido','err');return false}try{session?.disconnect?.()}catch{}panelPresent=false;status('Conectando…','');session=new window.LivePlusGameSDK.Session({storageKey:C.panelStorageKey,manifest:manifest()});session.addEventListener('connected',()=>{panelPresent=true;lastSeen=Date.now();status('Conectado','ok');try{session.sendState?.({scope:'initial',gameId:C.gameId,version:C.version})}catch{}});session.addEventListener('command',e=>onCommand(e.detail||{}));session.addEventListener('message',()=>{panelPresent=true;lastSeen=Date.now();emit()});session.addEventListener('transport',emit);session.addEventListener('reconnecting',()=>status('Reconectando…',''));session.addEventListener('lost',()=>{panelPresent=false;status('Conexão perdida','err')});session.addEventListener('rejected',e=>{panelPresent=false;status(e.detail?.reason||'Sessão recusada','err')});try{localStorage.setItem(C.panelCodeKey,format(code))}catch{}try{await session.connect(target.value);return true}catch(err){panelPresent=false;status(err?.message||'Falha ao conectar','err');return false}}
export function initPanelBridge(){const input=$('panelCode');window.LivePlusGameSDK?.installPasteBridge?.(input);try{const saved=clean(localStorage.getItem(C.panelCodeKey));if(saved&&input)input.value=format(saved)}catch{}input?.addEventListener('input',e=>e.target.value=format(e.target.value));input?.addEventListener('keydown',async e=>{if(e.key==='Enter')await connectPanel()});$('actionList').innerHTML=LIVE_ACTIONS.map(a=>`<i>${a.label}</i>`).join('');setInterval(()=>{if(panelPresent&&lastSeen&&Date.now()-lastSeen>30000&&session?.getTransport?.()==='offline'){panelPresent=false;status('Offline','')}emit()},1000);}
export function getPanelSession(){return session}
